### ISSUE TITLE
Carthage update dont work

### ISSUE THREAD

**Issue by dungi** [tatsu/OpenSphericalCamera#1]
Framework ist not shared - cant build it with carthage. Please add the shared-Option in your scheme.

**Comment by tatsu** [comment]
Hi, I'll manage it soon after my vacation. Of course, I always welcome pull requests. ^o^

**Comment by tatsu** [comment]
@dunqi It is shared in 598a3d28, or release 0.2.0 . It seems to be no problem.

Cheers!
