### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by chrismerron** [tatsu/OpenSphericalCamera#2]
Hi,
This isn't working too well in Swift 3 for iOS 10. Any plans to get it working for Swift 3?
Thanks
Chris

**Comment by tatsu** [comment]
Hi @chrismerron ,
Yes, I'm planning to update for Swift 3 on the best effort basis.
Please wait, or feel free to fork, or pull requests! ^^)/

Thanks

**Comment by tatsu** [comment]
It's been migrated to Swift 3. Please try release 3.0.0 !

Thanks
